First draft
codebuddies/newsletter pull request #1
Opened 2019-08-28 21:29 UTC by kvie

2019-08-29 07:22 UTC, lpatmo requested changes
Thank you so much, @kvie!! One small change requested (link to Ada's designs). Thank you!

2019-08-29 07:22 UTC, lpatmo commented on august2019.md
> +2. Shout-out to @Ada for coming up with some amazingly beautiful designs for CB Connect in [link].
Please link to https://sketch.cloud/s/PKPgL! :)

2019-08-30 01:57 UTC, kvie commented on august2019.md
> +2. Shout-out to @Ada for coming up with some amazingly beautiful designs for CB Connect in [link].
Done!

2019-08-30 03:03 UTC, lpatmo approved these changes

2019-08-30 03:03 UTC, lpatmo commented
Thanks so much @kvie!!

2019-08-30 03:04 UTC, merged